config/routes.rb
Rails.application.routes.draw do

  resources :capsules do
     resources :posts, only: [:create]
     resources :images, only: [:new, :create]
     resources :videos, only: [:create]
   end

  get 'capsules/delete', to: 'capsules#delete', as: 'capsules_remove'

  devise_for :users, :controllers => {registrations: "registrations"}

  root 'welcome#index'

end

app/models/capsule.rb
class Capsule < ActiveRecord::Base
  belongs_to :user

  has_many :posts, dependent: :destroy
  has_many :images, dependent: :destroy
  has_many :videos, dependent: :destroy
  mount_uploader :image, ImageUploader
  mount_uploader :video, VideoUploader

	accepts_nested_attributes_for :posts, :reject_if => lambda { |b| b[:body].blank? }

end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :capsule
	mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :capsule
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :capsules, dependent: :destroy

  

  def send_notification
  	AdminMailer.new_user(self).deliver
  end
  
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :capsule
  mount_uploader :video, VideoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  @new_user = User.new

  def after_sign_in_path_for(resource)
  	capsules_path
	end

end

app/controllers/capsules_controller.rb
class CapsulesController < ApplicationController
	before_action :set_capsule, only:[:show, :edit, :update, :destroy]
	before_action :set_new_user
	before_action :authenticate_user!, except:[:show]

	def index
		@capsules = current_user.capsules
	end

	def new
		@user = current_user
		@capsule = Capsule.new
	end

	def show
		@post = Post.new
		@image = Image.new
		release = @capsule.release_date.to_datetime
		reday = release.day
		remonth = release.month
		reyear = release.year
		date = Time.now
		day = date.day
		month = date.month
		year = date.year
		@year_remaining =  reyear - year 
		@month_remaining = remonth - month 
		@day_remaining = reday - day
	end

	def edit
	end

	def delete
		@capsules = current_user.capsules
	end

	def create
		@user = current_user
		@capsule = Capsule.new(params.require(:capsule).permit(:title, :release_date, :template).merge(user: current_user))
		if @capsule.save
			redirect_to @capsule, notice: 'You have created a new capsule'
		else
			render :index
		end
	end

	def update
		if @capsule.update(params.require(:capsule).permit(:post, :video, :image))
			redirect_to capsules_path, notice: "Your capsule has been updated"
		else
			render :show
		end
	end

	def destroy
		if @capsule.destroy
			redirect_to edit_user_registration_path
		else
			redirect_to capsules_remove_path, notice: "There was a problem deleting this capsule"
		end
	end

	private

	def set_capsule
		@capsule = Capsule.find(params[:id])
	end

	def set_new_user
		@new_user = User.new
	end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_user!

  def new
    @capsule = Capsule.find(params[:capsule_id])
    @image = Image.new(capsule_id: params[:capsule_id])
  end

  def create
    @capsule = Capsule.find(params[:capsule_id])
    @image = Image.new(params.require(:image).permit(:image).merge(capsule_id: params[:capsule_id]))
  	if @image.save
  		redirect_to @capsule
      p @image.image_url
  	else
  		redirect_to capsules_path
  	end
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :authenticate_user!

	before_action :set_new_user


	def new
		@capsule = Capsule.find(params[:capsule_id])
		@post = Post.new
	end

	def create
		@capsule = Capsule.find(params[:capsule_id])
  	@post = Post.new(params.require(:post).permit(:body, :title ).merge(capsule_id: params[:capsule_id]))
		if @post.save
			redirect_to @capsule
			flash[:notice] = 'Your memory has been stored in this capsule'
		else
			redirect_to @capsule
			flash[:login] = 'There was a problem with saving your memory'
		end 
	end

	private

  def post_params
    (params.require(:post).permit(:title, :body).merge(capsule_id: params[:capsule_id]))
  end

  def set_new_user
		@new_user = User.new
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	
    def edit
        @new_user = User.new
    end

   protected
    def after_sign_up_path_for(resource)
		new_capsule_path
		end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user!

  def new
  end

  def create
  	uploader = VideoUploader.new
  	if uploader.store!
  		redirect_to @capsule
  	else
  		redirect_to edit_capsule_path
  	end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @new_user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/capsules_helper.rb
module CapsulesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/capsules/_capsule.html.erb
<h1>New Capsule</h1>

<div class='capsuleform'>
  <%= form_for @capsule, :html => {:multipart => true}, method: :post do |f| %>    
    <%= f.text_field :title, placeholder: "Capsule title", :required => true %>

    <br>

    <%= f.text_field :release_date, id: "datepicker", placeholder: "When do you want this to be opened?", :required => true %>

    <br>

    <div class="templateChoice">
	    <h1>
			  Choose a template!
			</h1>

			<div class="cards">
			  <div class="card">
			    <div class="card-image">
			      <%= image_tag 'template_1.png' %>
			    </div>
			    
			    <div class="card-header">
			      Child Over Time
			    </div>
			    
			    <div class="card-copy">
			      <p>
        		Look at your child right now. If you could keep them this young and innocent would you? They will grow and feel pain, saddness and heartbreak, but also happiness, joy and all that life can offer.
     			 </p>
      			<p>
        		Capture your Child over Time in a sule. Open it up years from now and see how you felt on certain days, what picture or moment really got your attention that day. Keep them younger for a little bit longer.
      			</p>


			      <%= f.radio_button :template, 1 %>
			     </div>
			  </div>

			  <div class="card">
			    <div class="card-image">
			      <%= image_tag 'template_2.png' %>
			    </div>
			    
			    <div class="card-header">
			      Love Over Time
			    </div>
			    
			    <div class="card-copy">
			      <p>
        		Finding someone that you love is one of life's miracles. Cherish them, appreciate them whenever you can. Two souls, intertwined. 
      			</p>
      			<p>
        		Take a moment to save your thoughts, your movements together to reflect back on. The smaller shared details is where love can be found. A small moment of laughter remembered forever.
      			</p>

			      <%= f.radio_button :template, 2 %>
			    </div>
			  </div>

			  <div class="card">
			    <div class="card-image">
			      <%= image_tag 'template_3.png' %>
			    </div>
			    
			    <div class="card-header">
			      You Over Time
			    </div>
			    
			    <div class="card-copy">
			       <p>
        		Your journey through life finds meaning in all your interactions, your relationships, your pain and your happiness. To know who you are, you need to know who you were.
      			</p>
      			<p>
        		Capture every moment that impacted you, left you with thoughts that influence you. In the minutae of life is where beauty happens.
      			</p>

			      <%= f.radio_button :template, 3 %>
			    </div>
			  </div>
			</div>
		</div> 

    <%= f.submit "Create your capsule" %>
  <% end %>
</div>

app/views/capsules/_child.html.erb
<h2>Your Child grows up too quickly. Their personality develops in ways you could not imagine.</h2>
<h3> Let's start the story of your child today </h3>

<div id="example3" style="text-align:center">
  <%= form_for [@capsule, Post.new] do |f|%>
    <fieldset class = 'firstquestion'>
    <div class="wy-control-group">
      <%= f.label :body, 'How much did your child weigh at birth?' %>
      <%= f.text_field :body %>
    </div>
    </fieldset>

    <fieldset class = 'secondquestion'>
    <div class="wy-control-group">
      <%= f.label :body, 'Describe how your child looks' %>
      <%= f.text_field :body %>
    </div>
    </fieldset>


    <fieldset class = 'thirdquestion'>
    <div class="wy-control-group">
      <%= f.label :body, 'Tell your child how you feel about them today' %>
      <%= f.text_field :body %>
    </div>
    </fieldset>


    <fieldset class = 'fourthquestion'>
    <div class="wy-control-group">
      <%= f.label :body, 'What do you want the most for your child to know' %>
      <%= f.text_field :body %>
    </div>
    </fieldset>
  </form>

        <%= f.submit 'Submit' %>
</div>

<% end %>

app/views/capsules/_love.html.erb
<h2>Your Love blossoms as time goes on. Capture all the memories that you have.</h2>
<h3> Show your love for each other in a special way. Start holding those special moments forever </h3>

<%= form_for [@capsule, @post] do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <p>
        <%= msg %>
      </p>
    <% end %>
  <% end %>

  <div id="example3">
  <form id ="form3">
    <fieldset class = 'firstquestion'>
    <div class="wy-control-group">
      <%= f.label :body, 'What did you feel the first time you met your significant other?' %>
      <%= f.text_field :body %>
    </div>
    </fieldset>

    <fieldset class = 'secondquestion'>
    <div class="wy-control-group">
      <%= f.label :body, 'What is something about your significant other that you admire?'  %>
      <%= f.text_field :body %>
    </div>
    </fieldset>


    <fieldset class = 'thirdquestion'>
    <div class="wy-control-group">
      <%= f.label :body, 'Tell your significant other what attracts you to them' %>
      <%= f.text_field :body %>
    </div>
    </fieldset>


    <fieldset class = 'fourthquestion'>
    <div class="wy-control-group">
      <%= f.label :body, 'How does your significant other surprise you?' %>
      <%= f.text_field :body %>
    </div>
    </fieldset>
  </form>

        <%= f.submit 'Submit' %>
</div>

<% end %>

app/views/capsules/_templates.html.erb
<% f =  if local_assigns[:f].nil? %>
<h1>
  Choose a template!
</h1>

<div class="cards">
  <div class="card">
    <div class="card-image">
      <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/mountains.png" alt="">
    </div>
    
    <div class="card-header">
      Child Over Time
    </div>
    
    <div class="card-copy">
      <p>
        Look at your child right now. If you could keep them this young and innocent would you? They will grow and feel pain, saddness and heartbreak, but also happiness, joy and all that life can offer.
      </p>
      <p>
        Capture your Child over Time in a sule. Open it up years from now and see how you felt on certain days, what picture or moment really got your attention that day. Keep them younger for a little bit longer.
      </p>

      <%= f.radio_button :template, 1 %>
     </div>
  </div>

  <div class="card">
    <div class="card-image">
      <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/mountains-3.png" alt="">
    </div>
    
    <div class="card-header">
      Love Over Time
    </div>
    
    <div class="card-copy">
      <p>
        Finding someone that you love is one of life's miracles. Cherish them, appreciate them whenever you can. Two souls, intertwined. 
      </p>
      <p>
        Take a moment to save your thoughts, your movements together to reflect back on. The smaller shared details is where love can be found. A small moment of laughter remembered forever.
      </p>

      <%= f.radio_button :template, 2 %>
    </div>
  </div>

  <div class="card">
    <div class="card-image">
      <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/mountains-3.png" alt="">
    </div>
    
    <div class="card-header">
      You Over Time
    </div>
    
    <div class="card-copy">
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit.
      </p>

      <%= f.radio_button :template, 3 %>
    </div>
  </div>
</div>
    
<%= f.submit "Create your capsule" %>

<% end %>

app/views/capsules/_you.html.erb
<h2>On the Journey of life, change is inevitable. Capture how time grows you and makes you stronger.</h2>
<h3> Save all your past and help yourself become who you want to be </h3>

<%= form_for @capsule do |f| %>
<div id="example3">
  <form id ="form3">
    <fieldset class = 'firstquestion'>
    <div class="wy-control-group">
      <%= f.fields_for :posts, [Post.new] do |post| %>
      <%= post.label :body, 'How do you feel you have changed in the past year?' %>
      <%= post.text_field :body %>
      <% end %>
    </div>
    </fieldset>

    <fieldset class = 'secondquestion'>
    <div class="wy-control-group">
      <%= f.fields_for :posts, [Post.new] do |post| %>
      <%= post.label :body, 'Describe your biggest success to date' %>
      <%= post.text_field :body %>
      <% end %>
    </div>
    </fieldset>


    <fieldset class = 'thirdquestion'>
    <div class="wy-control-group">
      <%= f.fields_for :posts, [Post.new] do |post| %>
      <%= post.label :body, 'What is something that you want to do this year?' %>
      <%= post.text_field :body %>
      <% end %>
    </div>
    </fieldset>


    <fieldset class = 'fourthquestion'>
    <div class="wy-control-group">
      <%= f.fields_for :posts, [Post.new] do |post| %>
      <%= post.label :body, 'How have you surprised yourself in the past year?' %>
      <%= post.text_field :body %>
      <% end %>
    </div>
    </fieldset>
  </form>

        <%= f.submit 'Submit' %>
</div>

<% end %>

app/views/capsules/edit.html.erb
	<% if @capsule.template = 1 %>
		<%= render partial: 'child' %>
	<% elsif @capsule.template = 2 %>
		<%= render partial: 'love' %>
	<% elsif @capsule.template = 3 %>
		<%= render partial: 'you' %>
<% end %>

app/views/capsules/index.html.erb
<div class="flex-boxes">
	<% current_user.capsules.each do |capsule| %>
		<div class = "flex-box">
		  <%= link_to capsule.title, capsule_path(capsule) %>
		  
	   <!--  <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_2_dark.png" alt=""> -->  	
			
			<p>
				<%= capsule.release_date.month %>/<%= capsule.release_date.day %>/<%= capsule.release_date.year %>
			</p>
		</div>
	<% end %>
</div>

app/views/capsules/new.html.erb
<div class="newCapsule">
	<%= render 'capsule' %>
</div>

app/views/capsules/show.html.erb
<div class="show">
	<% if @capsule.release_date > Time.now %>
		<div class="dateTime">
			<% if @capsule.release_date.day > 01 %>
				<h1>
					This capsule will open in
					<%= @year_remaining %> years, <%= @month_remaining %> months, and <%= @day_remaining %> days
				</h1>
			<% elsif @capsule.release_date.day == 01 %>
				<h1>
					This capsule will open in
					<%= @year_remaining %> years, <%= @month_remaining %> months, and <%= @day_remaining %> day
				</h1>
			<% end %>
		</div>
	<% else %>
		<div class="grid-items">
			<% @capsule.posts.each do |t| %>
				<a href="javascript:void(0)" class="grid-item">
					<h1>
						<%= t.title %>
					</h1>
					
					<p>
						<%= t.body %>
					</p>
					
					<p>
						<%= "#{t.created_at.month}/#{t.created_at.day}/#{t.created_at.year}" %>
					</p>
				</a>
			<% end %>

			<% @capsule.images.each do |t| %>
				<a href="javascript:void(0)" class="grid-item grid-item-big grid-item-image">
					<p>
						<%= t.title %>
					</p>
					<%= image_tag t.image_url.to_s, class: "capsuleImages" %>

				</a>

			<% end %>
			
			<% if @capsule.video? %>
				<a href="javascript:void(0)" class="grid-item grid-item-big">
					<%= video_tag @capsule.video_url.to_s %>
				</a>
			<% end %>
		</div>
	<% end %>

	<% if @capsule.user == current_user %>
		<div class="submits">
			<h1>
				Add a memory to the time capsule
			</h1>
				
			<div class="mediaSubmit">
				<%= form_for [@capsule, @image], :html => {:multipart => true}, class: 'newMedia' do |f| %>
					<!-- <fieldset> -->
					<h2>
						<%= f.label :name, "Captured memory" %>
					</h2>

					
					<p class="image field">
						<%= f.file_field :image %>
					</p>

					<div class="photoSubmit">
						<%= f.submit %>	
					</div>
					<!-- </fieldset> -->
				<% end %>
			</div>
			
			<div class="postSubmit">
				<%= form_for [@capsule, @post] do |f| %>
					<% if @post.errors.any? %>
						<% @post.errors.full_messages.each do |msg| %>
					   <p>
						   <%= msg %>
					   </p>
						<% end %>
					<% end %>

					<div class="memory">
				  <!--   <fieldset class = 'firstquestion'> -->
					    <div class="wy-control-group">
					    	<%= f.label :body, 'Submit a memory' %>
					      
					      <%= f.text_area :body, placeholder: 'Write about something that happened today, add a photo or even a video' %>
					      
					      <%= f.hidden_field :unique, value: 1 %>
					      
					      <%= f.submit 'Submit',  :onclick => "ReplaceForm()" %>
					    </div>
				    <!-- </fieldset> -->
					</div>
				<% end %>
			</div>
		</div>
	<% end %>
</div>

app/views/capsules/test.html.erb
<% if @capsule.release_date > Time.now %>
	<h1>
		This capsule will open in
		<%= @year_remaining %> years
		<%= @month_remaining %> months and
		<%= @day_remaining %> days
	</h1>
<% else %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sule</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <link href='http://fonts.googleapis.com/css?family=Jura' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js" type="text/javascript"></script>
  
  <%= javascript_include_tag 'application'  %>
	<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.5.5/slick-theme.css"/>
	<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.5.5/slick.css"/>
  <%= favicon_link_tag %>
</head>
<body>

    <div class='header'>
      <h1 style="display: inline-block; a: color: black; text-decoration: none;"><%= link_to 'Sulé', capsules_path %></h1>
      <nav>
        <ul>
          <% if user_signed_in? %>
              <div class="dropdown">
                <div class="dropdown-container">
                  <p class="dropdown-description"><i><%=current_user.email%></i></p>
                  <p class="dropdown-button"><%= image_tag('Black_wrench_24.png')%></p>
                  <ul class="dropdown-menu dropdown-select">
                    <li><%=link_to 'Logout', destroy_user_session_path, method: :delete%></li>
                    <li><%=link_to 'New Capsule', new_capsule_path %></li>
                    <li><%=link_to 'Capsules', capsules_path%></li>
                    <li><%=link_to 'Settings', edit_user_registration_path %></li>
                  </ul>
                </div>
              </div>
              <% else %>
              <li>
                <label for="modal-1"><div class="modal-trigger">Login / Signup</div></label>
              </li>

          <% end%>
        </ul>
      </nav>
    </div>

    <!-- modal stuff -->
    <div class="modal">
      <input class="modal-state" id="modal-1" type="checkbox" />
      <div class="modal-fade-screen">
        <div class="modal-inner">
          <div class="modal-close" for="modal-1">Close</div>
          <hr>
          <div class="modal-content">
            <h2>Log in</h2>
            <%= form_for User.new, url: user_session_path do |f| %>
                <div class="field">
                  <%= f.email_field :email, autofocus: true, placeholder: 'email' %>
                </div>

                <div class="field">
                  <%= f.password_field :password, autocomplete: "off", placeholder: 'password' %>
                </div>

                <div class="actions">
                  <%= f.submit "Log in" %>
                </div>
                <div class="actions">
               <%= link_to "Forgot your password?", new_password_path(:user) %>
             </div>
            <% end %>
            <hr>
            <h2>Sign up</h2>

            <%= form_for User.create, url: user_registration_path do |f| %>

                <div class="field">
                  <%= f.email_field :email, autofocus: true, placeholder: 'email'%>
                </div>

                <div class="field">
                  <% if @minimum_password_length %>
                      <em>(<%= @minimum_password_length %> characters minimum)</em>
                  <% end %><br />
                  <%= f.password_field :password, autocomplete: "off", placeholder: 'password' %>
                </div>

                <div class="field">
                  <%= f.password_field :password_confirmation, autocomplete: "off", placeholder: 'password confirmation' %>
                </div>

                <div class="actions">
                  <%= f.submit "Sign up" %>
                </div>
            <% end %>
            <hr>
          </div>
        </div>
      </div>
    </div>
    <div class="bgimg">
      <div class="yield">

        <% if flash[:notice] %> 
        <p id="notice"><%= notice %></p>
        <% end %>
        <% if flash[:alert] %>
        <p id="alert"><%= alert %></p>
        <% end %>
        <%= yield %>
      </div>
    </div>


<script type="text/javascript" src="//cdn.jsdelivr.net/jquery.slick/1.5.5/slick.min.js"></script>
</body>
</html>

app/views/posts/new.html.erb
<h2>Your Child grows up too quickly. Their personality develops in ways you could not imagine.</h2>


<%= form_for [@capsule, @post] do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <p>
        <%= msg %>
      </p>
    <% end %>
<% end %>


<div id="example3" style="text-align:center">
  <form id ="form3">
    <fieldset class = 'firstquestion'>
      <div class="wy-control-group">
      	<%= f.label :body, 'How much did your child weigh at birth?' %>
        
        <%= f.text_field :body %>
        
        <%= f.hidden_field :unique, value: 1 %>
        
        <%= f.submit 'Submit',  :onclick => "ReplaceForm()" %>
      </div>
    </fieldset>
  </form>
</div>

<div id="for_replacement" style="display:none;">

    <fieldset id = 'secondquestion'>
    <div class="wy-control-group">
      <%= f.label :body, 'Describe how your child looks' %>
      <%= f.text_field :body %>
      <%= f.hidden_field :unique, value: 2 %>
      <%= f.submit 'Submit' %>
    </fieldset>
  </div>
  </form>
</div>

  
  <script type="text/javascript">
function ReplaceForm()
{
// Three places to customize:

// Specify the id of the form.
var IDofForm = "form3";

// Specify the id of the div containing the form.
var IDofDivWithForm = "example3";

// Specify the id of the div with the content to replace the form with.
var IDforReplacement = "for_replacement";

// End of customizations.

// This line submits the form. (If Ajax processed, call Ajax function, instead.)
document.getElementById(IDofForm).on('ajax:success');

// This replaces the form with the replacement content.
document.getElementById(IDofDivWithForm).innerHTML = document.getElementById(IDforReplacement).innerHTML;
}
</script>
<% end %>

app/views/shared/_favicon.html.erb
  <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
  <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
  <link rel="manifest" href="/manifest.json">
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
  <meta name="theme-color" content="#ffffff">

app/views/videos/new.html.erb
<h1>Videos#new</h1>
<p>Find me in app/views/videos/new.html.erb</p>

app/views/welcome/_new.html.erb
<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="field">
    <%= f.label :email %>

    <br>
    
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %>
    
    <br>

    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <% if devise_mapping.rememberable? -%>
    <div class="field">
      <%= f.check_box :remember_me %>
    
      <%= f.label :remember_me %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit "Log in" %>
  </div>
<% end %>


<%= form_for @new_user, url: user_registration_path do |f| %>
  <div class="field">
    <%= f.label :email %>

    <br>
    
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %>
    
    <% if @minimum_password_length %>
        <span class="emb">
          (<%= @minimum_password_length %> characters minimum)
        </span>
    <% end %>

    <br>
    
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>

    <br>
    
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/welcome/index.html.erb
<!--<div class ='view'>-->

  <!--<div class = 'image'>-->
    <!--&lt;!&ndash;<img src="http://wallarthd.com/wp-content/uploads/2014/09/Beautiful-Clock-Macro-Wallpaper-For-Android.jpg">&ndash;&gt;-->
  <!--</div>-->

  <!--<div class = 'image2'>-->
    <!--&lt;!&ndash;<img src="http://wallarthd.com/wp-content/uploads/2014/09/Beautiful-Clock-Macro-Wallpaper-For-Android.jpg">&ndash;&gt;-->
  <!--</div>-->
<!--</div>-->
<video width="400" id="bgvid" src="<%= asset_path('videos/clocklapse.webm') %>" autoplay loop poster="./images/clocklapse.png">
  <!-- WCAG general accessibility recommendation is that media such as background video play through only once. Loop turned on for the purposes of illustration; if removed, the end of the video will fade in the same way created by pressing the "Pause" button  -->
<div class="image-gradient-dynamic">
  <img src="http://wallarthd.com/wp-content/uploads/2014/09/Beautiful-Clock-Macro-Wallpaper-For-Android.jpg" alt="">
  <div class="overlay"></div>
  <div class="copy">
   		<p> Memories are fleeting </p>
			<p>A few reasons why this product is worth using, who it's for and why they need it.</p>
  </div>
</div>
</video>
<div class = 'mainWords'>
  <h1>Change</h1>
  <hr>
  <h1>Time</h1>
</div>